-- Manhaj schema · 017_table_comments.sql
-- ============================================================================
-- Add descriptions to all tables that don't already have one.
-- Applied via Supabase MCP on 2026-06-29.
--
-- No _omr columns remain anywhere in the schema — all were renamed in
-- 014_parent_sweep_corrections (invoice_lines.amount_aed,
-- invoices.amount_owed_aed, activities.cost_aed).
--
-- Tables with existing comments left untouched:
--   ai_usage_ledger, attendance_marks, audit_log, bell_periods,
--   consent_records, rooms, rubric_scores, terms, timetable_slots,
--   user_schools
-- ============================================================================

COMMENT ON TABLE academic_years          IS 'School academic years. Root scope for most data; almost every tenanted table links here to partition records by year.';
COMMENT ON TABLE activities              IS 'School trips, events, and workshops. Drives the P4 permission-slip consent form; parents respond once per activity per student.';
COMMENT ON TABLE ai_briefings            IS 'Cached daily morning briefing generated by Claude for the principal. Generated on a background cron and read at zero AI cost on page load.';
COMMENT ON TABLE announcements           IS 'School-wide announcements posted by admins. Audience field controls visibility to teachers, parents, or students.';
COMMENT ON TABLE applicants              IS 'School admissions pipeline. Prospective students move through stages (new → review → offer → accepted) before being converted to a student record.';
COMMENT ON TABLE application_grades      IS 'Predicted and actual exam scores (IB, SAT, IELTS, etc.) per university application. validated_by tracks school staff sign-off before scores feed the match model.';
COMMENT ON TABLE applications            IS 'University applications for senior students (Grade 10+). Tracks stage, fit tag, document progress, and links to grades, personal statements, and references.';
COMMENT ON TABLE assessment_results      IS 'One row per student per assessment. The score source for the parent digest grade card, student goals, and the rubric AI suggestion.';
COMMENT ON TABLE assessments             IS 'Quizzes, tests, exams, and homework tasks defined by teachers. Drives the student weekly planner and parent digest.';
COMMENT ON TABLE behaviour_notes         IS 'Teacher-logged behaviour observations (positive recognition or incidents). Feeds at-risk flags, parent digest timeline, and T6 substitute callouts.';
COMMENT ON TABLE comm_drafts             IS 'AI-drafted parent communications queued for approval and send. status moves draft → sent; sent_message_id is the Resend receipt.';
COMMENT ON TABLE comm_templates          IS '17 Manhaj default message templates plus school-custom ones. Controls tone, word-count cap, required slots, and AI prompt per template.';
COMMENT ON TABLE course_catalog          IS 'Master list of courses/subjects the school offers. Referenced by elective bundles and course-selection forms.';
COMMENT ON TABLE course_selection_forms  IS 'Elective and course-selection forms sent to parents each year. Gated by section mapping; drives the course-selection workflow.';
COMMENT ON TABLE course_selection_picks  IS 'Parent-submitted course choices for a student against a course-selection form. One pick row per elective option selected.';
COMMENT ON TABLE elective_bundles        IS 'Groups of elective options presented together on a course-selection form (e.g. "Science track", "Arts track").';
COMMENT ON TABLE elective_options        IS 'Individual elective choices within a bundle. Parents or students pick one option per bundle.';
COMMENT ON TABLE goal_checkins           IS 'Self-reported tick-ins or auto progress captures for student goals. The only stored progress data; computed goals derive from spine tables on read.';
COMMENT ON TABLE goal_reflections        IS 'Monthly student reflection on their goals. Audience-scoped (student / teacher / opt-in parent); feeds the parent monthly report.';
COMMENT ON TABLE invitations             IS 'Pending admin and advisor invitations. Token is verified at the magic-link callback; row expires after 7 days.';
COMMENT ON TABLE invoice_lines           IS 'Flat-amount line-item breakdown of an invoice (tuition, bus, lunch, trips, deposits). Sourced from the school finance file; no unit pricing.';
COMMENT ON TABLE invoices                IS 'Fee invoices per student per installment, loaded from the school finance file. Manhaj is a display layer only; status reflects the school''s latest upload.';
COMMENT ON TABLE job_applicants          IS 'Staff/HR hiring pipeline. Tracks candidates applying to open job postings. Separate from the school-admissions applicants table.';
COMMENT ON TABLE job_postings            IS 'Open staff positions at the school. Referenced by job_applicants in the HR hiring funnel.';
COMMENT ON TABLE lesson_followups        IS 'Teacher to-dos tied to a lesson: priority tasks, concept notes, PTC reminders, and handoff notes routed to another teacher via tag.';
COMMENT ON TABLE lessons                 IS 'Lesson plans (plan_kind=weekly_plan) and post-lesson summaries (post_summary) written by teachers. Weekly plans feed the T6 substitute sheet.';
COMMENT ON TABLE notifications           IS 'In-app notifications for teachers, parents, and students. Ephemeral; complement to email delivery via Resend.';
COMMENT ON TABLE parents                 IS 'Parent and guardian profiles. One parent may be linked to multiple students via student_parents. Receives comms and invoices.';
COMMENT ON TABLE permission_slips        IS 'Parent responses to trip/activity consent requests. One row per student per activity; signed_name + signed_at record the typed-name legal signature.';
COMMENT ON TABLE personal_statements     IS 'Versioned university personal statement drafts. Counsellor-reviewed before any AI feedback is shared; version tracks iteration history.';
COMMENT ON TABLE regulatory_report_catalog IS 'Registry of MoE / regulator-mandated report types (enrolment return, attendance summary). Scaffolded in P1; generators added after MoE research completes.';
COMMENT ON TABLE report_archive          IS 'Stored copies of sent reports and communications with a retention clock. delete_after drives the compliance-retention cleanup job (2–3 year window).';
COMMENT ON TABLE report_submissions      IS 'Tracks which regulatory report instances have been submitted to which regulator and on what date.';
COMMENT ON TABLE risk_flags              IS 'At-risk student flags routed to an owner (advisor or homeroom teacher). RLS scopes advisors to their own flags; admins see all. Status: open → in_progress → resolved.';
COMMENT ON TABLE rubric_criteria         IS 'The six Manhaj rubric axes (analytical, creative, oral, written, participation, homework). ai_suggested marks data-led axes vs pure-judgement axes.';
COMMENT ON TABLE rubrics                 IS 'Rubric definitions (Manhaj default + school-custom). Parent of rubric_criteria rows that define the axes and scoring scale.';
COMMENT ON TABLE school_admins           IS 'Admin and advisor team members. status tracks active / pending-invite / inactive; invited_by records the chain of invitation.';
COMMENT ON TABLE schools                 IS 'One row per tenant school. The root anchor for all RLS policies via the tenant_id() JWT function.';
COMMENT ON TABLE section_subjects        IS 'Maps a section to the subjects it studies and the weekly period volume. Primary curriculum-split input for the timetable solver and lesson pre-seed.';
COMMENT ON TABLE sections                IS 'Class groups within a school year (e.g. G5B, 11AS). is_mapped gates report sends; head_teacher_id is the homeroom teacher.';
COMMENT ON TABLE source_imports          IS 'Log of raw data file imports (CSV/XLSX) from the school. Tracks what was ingested and when for reconciliation and re-upload detection.';
COMMENT ON TABLE staff_absences          IS 'Teacher sick-leave and absence requests. Principal approval triggers the substitute finder and auto-builds the T6 handoff sheet.';
COMMENT ON TABLE staffing_categories     IS 'School-defined teacher workload categories (e.g. teaching_full, teaching_part, admin). Drives HR grouping and workload reporting.';
COMMENT ON TABLE student_enrollments     IS 'Links students to their class section for a given academic year. The roster source for attendance marking and timetable entry.';
COMMENT ON TABLE student_goals           IS 'Personal goals set by the student or co-set by a teacher/counsellor. Progress is always computed on read from spine tables — never stored.';
COMMENT ON TABLE student_health          IS 'Allergy, medical condition, and emergency-contact record per student. System-of-record for T6 substitute callouts and P4 trip-consent health check.';
COMMENT ON TABLE student_parents         IS 'Links students to their parents/guardians with relationship type. is_primary flags the main contact; drives the P6 sibling-comparison household view.';
COMMENT ON TABLE student_test_scores     IS 'Standalone standardised test scores (SAT, IELTS, AP, etc.) not tied to a school-run assessment. Feeds the S3 university application tracker.';
COMMENT ON TABLE students                IS 'Student profiles. advisor_id routes at-risk flags to the responsible advisor; withdrawn_on + withdrawn_reason record confirmed leavers.';
COMMENT ON TABLE study_blocks            IS 'Student-edited afternoon study-plan overlay for the S2 weekly planner. Only the drag-adjusted arrangement is stored; timetable data is never duplicated here.';
COMMENT ON TABLE subjects                IS 'Subject definitions (Maths, Science, Arabic, etc.). Referenced across timetable slots, assessments, rubric scores, and the teacher load matrix.';
COMMENT ON TABLE substitute_sheets       IS 'Auto-generated handoff sheet artifacts for substitute teachers. Versioned; ack_at records when the sub acknowledged reading it before class.';
COMMENT ON TABLE substitutions           IS 'Per-slot substitute assignments when a teacher is absent. Complements staff_absences.sub_teacher_id for slot-level sub tracking.';
COMMENT ON TABLE teacher_contracts       IS 'Annual period cap and contract terms per teacher per year. weekly_period_cap feeds the v_teacher_load view and the CP-SAT timetable solver.';
COMMENT ON TABLE teacher_references      IS 'Reference letters authored by teachers for university applications. base_reference_id supports per-school adaptations from a master reference.';
COMMENT ON TABLE teacher_section_subject IS 'Teacher load matrix: who teaches which subject to which section and how many periods per week. The primary input for the CP-SAT timetable solver.';
COMMENT ON TABLE teachers                IS 'Teacher profiles. staffing_category_id sets the workload group; employment_status tracks active / applicant / offer stages.';
COMMENT ON TABLE university_outcomes     IS 'Historic school leaver outcomes (kind=historic) and university-sourced benchmarks (kind=benchmark). Feeds the S3 match model and placement insights panel.';
